
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

### get profile
GET http://localhost:8080/api/v1/auth/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGQyMDljODkyMmQ2YjJiZjkwNzc2NGQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc1ODU5NTU0MCwiZXhwIjoxNzU4NjgxOTQwfQ.RuZISvB7FHaqsrnh15tCk6Dnrirk0IgiShcrhv5dGTA
